Repository CMEPW/Smersh, pull requests merged in 2021-03, with the labels that each got.

#55 [FEAT] Issues 34 & 37 - Add search bars and pagination on generic list
  api/config/packages/api_platform.yaml
  api/src/Entity/Client.php
  api/src/Entity/Host.php
  api/src/Entity/Impact.php
  api/src/Entity/Mission.php
  api/src/Entity/User.php
  api/src/Entity/Vuln.php
  api/src/Filter/MissionTypeFilter.php
  api/src/Traits/TypeTrait.php
  client/src/app/app.component.ts
  client/src/app/app.module.ts
  client/src/app/components/add-vulns-to-host-external/add-vulns-to-host-external.component.ts
  client/src/app/components/clients/clientsList.component.ts
  client/src/app/components/conclusion/conclusion.component.ts
  client/src/app/components/generic/list/generic-list.component.html
  client/src/app/components/generic/list/generic-list.component.ts
  client/src/app/components/hosts/hostsList.component.ts
  client/src/app/components/mission-create/mission-create.component.ts
  client/src/app/components/mission-edit/mission-edit.component.ts
  client/src/app/components/mission-single/mission-single.component.html
  client/src/app/components/side-bar/side-bar.component.html
  client/src/app/components/side-bar/side-bar.component.scss
  client/src/app/components/users/usersList.component.ts
  client/src/app/components/vulns-create/vulns-create.component.ts
  client/src/app/services/abstract.ts
  client/src/app/services/filter.service.ts
  client/src/app/services/theme.service.ts
  client/src/app/services/vulns.service.ts
  client/src/styles.scss
Labels: Done - Merge soon, RFR

#50 [CSS] - Better form to add vuln on host
  client/src/app/components/add-vulns-to-host-external/add-vulns-to-host-external.component.html
  client/src/app/components/add-vulns-to-host-external/add-vulns-to-host-external.component.scss
Labels: Done - Merge soon, RFR

#60 [Feat] - Add possibility to dump mission data as json-ld file
  client/src/app/components/mission-single/mission-single.component.html
  client/src/app/components/mission-single/mission-single.component.scss
  client/src/app/components/mission-single/mission-single.component.ts
Labels: RFR

#64 [Typo] - Dashboard fix
  client/src/app/components/mission-my/mission-my.component.html
Labels: RFR

#65 [README] - update preview report and add new demo gif
  README.md
  img/demo.gif
  img/rapport-preview2.png
  img/searchbar.png
Labels: RFR

#81 [Feat] - Add possibility to add ip with cidr
  api/src/Controller/UploadHostController.php
  api/src/Entity/Host.php
Labels: RFR

#76 [Typo] - change button name ( report )
  client/src/app/components/mission-single/mission-single.component.html
Labels: RFR

#73 [CSS] - Larger navbar
  client/src/app/components/side-bar/side-bar.component.html
  client/src/app/components/side-bar/side-bar.component.scss
Labels: RFR

#75 [CSS] - Space item navbar
  client/src/app/components/side-bar/side-bar.component.html
  client/src/app/components/side-bar/side-bar.component.scss
Labels: RFR

#74 [Form] - Clean input after submit
  client/src/app/components/mission-single/mission-single.component.ts
Labels: RFR

#72 [Display] - Display filename of uploaded file
  client/src/app/components/mission-single/mission-single.component.html
Labels: RFR

#77 [Display] - Add mission count to dashboard
  client/src/app/app.module.ts
  client/src/app/components/mission-my/mission-my.component.html
  client/src/app/components/mission-my/mission-my.component.ts
Labels: work in progress

#69 [Feat] - Download BurpSuite config file
  client/src/app/components/mission-single/mission-single.component.html
  client/src/app/components/mission-single/mission-single.component.ts
  client/src/app/services/configService.ts
  client/src/assets/burp.json
Labels: RFR

#71 [Fix] - Refresh view using ngOnInit after upload file
  client/src/app/components/mission-single/mission-single.component.ts
Labels: RFR
